name: Update Version Badge

on:
  push:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version from package.xml
        id: get_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<version>)[^<]+" package.xml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Print badge line
        run: grep 'https://img.shields.io/badge/Version' README.md || echo "Badge not found"
        

      - name: Update README.md
        run: |
          sed -i "s|![Version](https://img.shields.io/badge/Version-[^ )]*-blue)|![Version](https://img.shields.io/badge/Version-${{ env.VERSION }}-blue)|g" README.md

      - name: Check for changes
        run: git diff README.md || echo "No differences detected"
      
      - name: Commit changes
        run: |
          git config --local user.email "ckyb63@gmail.com"
          git config --local user.name "ckyb63"
          git add README.md
          git commit -m "Update version badge to ${{ env.VERSION }}" || echo "No changes to commit"
          git push
