name: Update Version Badge

on:
  push:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version from package.xml
        id: get_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<version>)[^<]+" package.xml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Update setup.py version
        run: |
          sed -i "s/version='[0-999]*\.[0-9999]*\.[0-999]*'/version='${{ env.VERSION }}'/" setup.py

      - name: Print badge line
        run: grep 'https://img.shields.io/badge/Version' docs/README.md || echo "Badge not found"
        
      - name: Normalize line endings
        run: sed -i 's/\r//' docs/README.md
      
      - name: Update README.md
        run: |
          sed -i 's|https://img.shields.io/badge/Version-[^)-]*-blue|https://img.shields.io/badge/Version-${{ env.VERSION }}-blue|g' docs/README.md

      - name: Print README.md after update
        run: cat docs/README.md
        
      - name: Check for changes
        run: git diff docs/README.md || echo "No differences detected"
      
      - name: Commit changes
        run: |
          git config --local user.email "ckyb63@gmail.com"
          git config --local user.name "ckyb63"
          git add docs/README.md setup.py  # Add setup.py to the commit
          git commit -m "Update ${{ env.VERSION }}" || echo "No changes to commit" 
          git push